[bar/main]
include-file = "~/.config/polybar/fonts.ini"
monitor = ${env:MONITOR:}

width = 100%
height = 25
bottom = false

background = ${colors.background}
foreground = ${colors.foreground}

padding-left = 1
padding-right = 1
line-size = 1

; tray-position = right
; tray-background = ${colors.background}

border-top-size = 5
border-bottom-size = 5
border-top-color = ${colors.background}
border-bottom-color = ${colors.background}

modules-left = round-left powermenu round-right empty-space round-left workspaces round-right
modules-center = round-left time colored-empty-space weather round-right
modules-right =   empty-space  round-left   network round-right  empty-space round-left backlight colored-empty-space  audio round-right empty-space round-left cpu colored-empty-space  memory round-right empty-space round-left battery round-right 

cursor-click = pointer
cursor-scroll = ns-resize

# override-redirect = true
