[module/workspaces]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false
;strip-wsnumbers = true

; Only show workspaces on the same output as the bar
pin-workspaces = true

label-mode-padding = 0
label-mode-foreground = ${colors.foreground}
label-mode-background = ${colors.group-background}

; focused = Active workspace on focused monitor
label-focused = %index%
label-focused-foreground = ${colors.foreground}
label-focused-background = ${colors.group-background}
label-focused-underline= ${colors.color10}
label-focused-padding = 0
label-focused-padding-left = 1
label-focused-padding-right = 1
label-focused-font = 1

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-background = ${self.label-focused-background}
label-unfocused-padding = 0
label-unfocused-padding-left = 1
label-unfocused-padding-right = 1

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-background = ${self.label-focused-background}
; label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}
label-visible-padding-left= 1
label-visible-padding-right= 1

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-background = ${colors.color9}
label-urgent-padding = 1

# ======================================

[module/empty-space]
type = custom/text
content = "  "

# =======================================

[module/colored-empty-space]
type = custom/text
content = "  "
content-background = ${colors.group-background}

# =======================================

[module/round-left]
type = custom/text
content = %{T3}%{T-}
content-foreground = ${colors.group-background}

# =======================================

[module/round-right]
type = custom/text
content = %{T3}%{T-}
content-foreground = ${colors.group-background}

# =======================================

[module/powermenu]
type = custom/text
content  = "     "

content-foreground = ${colors.color1}
content-background = ${colors.group-background}
; content-underline = ${colors.color1}

click-left = ~/.config/rofi/bin/rofi_powermenu

[module/time]
type = internal/date
interval = 60

format = <label>
format-background = ${colors.group-background}
format-foreground = #cba6f7

date = %H:%M %a, %b %d%{F-}
time-alt =  %H:%M 
label = %{A3:kitty -e tty-clock -cbt -C 4:} %date%%time% %{A}

[module/weather]
type = custom/script
exec = ~/.config/polybar/openweathermap-simple
exec-if = ping openweathermap.org -c 1
interval = 600
; label-font = 3
format-background = ${colors.group-background}
format-foreground = #cba6f7

# =======================================

[module/audio]
type = internal/pulseaudio
format-volume = %{A3:pavucontrol-qt:} <ramp-volume> <label-volume> %{A}
label-muted = %{A3:pavucontrol-qt:} 婢 0% %{A}
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 墳
label-volume-foreground = #89DCEB
label_underline = #89DCEB
format-volume-background = ${colors.group-background} 
format-volume-foreground = #89DCEB
format-muted-foreground = #F28FAD
format-muted-background = ${colors.group-background}
format-muted-padding = 1

# =======================================

[module/cpu]
type = internal/cpu
interval = 0.5

format-prefix ="  "
format =  <label>

label = %{A1:kitty -e btop:} %percentage%% %{A}
format-background = ${colors.group-background}
format-foreground = #F8BD96
format-prefix-foreground = #F8BD96

# =======================================

[module/temperature]
type = internal/temperature
interval = 0.5
hwmon-path = /sys/class/hwmon/hwmon4/temp1_input
label = " %temperature-c%"
format = <label>
format-background = ${colors.group-background}
format-foreground = #F8BD96

# =======================================

[module/memory]
type = custom/script
exec = free -m | sed -n 's/^Mem:\s\+[0-9]\+\s\+\([0-9]\+\)\s.\+/\1/p'
interval = 0.5
format = <label>
format-prefix = "﬙ "
label = %{A1:kitty -e btop:} %output% MB %{A}
# label-padding = 1
format-prefix-foreground = #F8BD96
format-label-foreground = #F8BD96
format-background = ${colors.group-background}
format-foreground = #F8BD96

# =======================================

[module/network]
type = internal/network
interface = wlo1
interface-type = wireless
interval = 1
format-connected =  <label-connected> 
label-connected = %{A1:nm-connection-editor:} 直 %essid% %{A} 
label-connected-foreground = #B5E8E0
label-connected-background = ${colors.group-background}
label-disconnected = %{A1:nm-connection-editor:} 睊 %{A}
label-disconnected-background = ${colors.group-background}
label-disconnected-foreground = #F28FAD

# =======================================

[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP1
full-at = 99
poll-interval = 0.5
;format-background = ${colors.group-background}

format-charging = <animation-charging> <label-charging>
label-charging = %percentage% %
format-charging-foreground = ${colors.color4}
format-charging-background = ${colors.group-background}

format-discharging = <ramp-capacity> <label-discharging>  
label-discharging = %percentage%%
format-discharging-foreground = ${colors.color4}
format-discharging-background = ${colors.group-background}

format-full-prefix = "  "
format-full-prefix-foreground = #ABE9B3
format-foreground = #ABE9B3
format-full-background = ${colors.group-background}

label-discharging-foreground = #ABE9B3
ramp-capacity-foreground =  #ABE9B3
label-charging-foreground = #ABE9B3

label-padding = 1

ramp-capacity-0 = "  "
ramp-capacity-1 = "  "
ramp-capacity-2 = "  "
ramp-capacity-3 = "  "
ramp-capacity-4 = "   "

animation-charging-0 = "  "
animation-charging-1 = "  "
animation-charging-2 = "  "
animation-charging-3 = "  "
animation-charging-4 = "  "

animation-charging-foreground = #ABE9B3
animation-charging-framerate = 750

format-charging-padding = 1
format-discharging-padding = 1

# =======================================

[module/mpd]
type = internal/mpd
host = 127.0.0.1
port = 6600
interval = 2

# 1: left click -> play/pause
# 3: right click -> open ncmpcpp
# 4: scroll up -> next song
# 5: scroll down -> prev song
label-song = %{A1:mpc toggle:}%{A3:st -e ncmpcpp:}%{A4:mpc next:}%{A5:mpc prev:} %artist% - %title% %{A}%{A}%{A}%{A}
format-playing = " <label-song>"
format-paused = " <label-song>"
format-stopped = ""
format-playing-foreground = #989cff
format-paused-foreground = ${colors.foreground}

# ========================================

[module/spotify]
type = custom/script
interval = 1
format-prefix = "阮 "
format-prefix-foreground = #ABE9B3
;format-foreground = #ABE9B3
format = <label>
exec = python ~/.config/polybar/spotify-status.py -f '{song} | {artist}'
;format-underline = #ABE9B3
;control players (optional)
click-left = playerctl --player=spotify play-pause 
click-right = playerctl --player=spotify next 
click-middle = playerctl --player=spotify previous 

# ========================================

[module/wired-network]
type = internal/network
interface = enp0s31f6
interface-type = wired
interval = 1
format-connected = <label-connected> 
format-disconnected = <label-disconnected> 
label-connected = "  "
label-disconnected = "  "
label-connected-foreground = #B5E8E0
label-disconnected-foreground = #F28FAD
format-connected-background = ${colors.group-background}
format-disconnected-background = 1e1e2e

# ========================================

[module/speedtest]  
type = custom/script   
click-left = "~/.config/polybar/polybar-speedtest"  
format-prefix = 龍
format-prefix-foreground = {colors.foreground}

# ========================================

[module/backlight]
type = internal/backlight
card = intel_backlight
use-actual-brightness = true
enable-scroll = true
format =" <ramp> <label>"
label = "%percentage%%"
ramp-foreground = #89DCEB
label-foreground = #89DCEB
format-background = ${colors.group-background}

; only applies if <ramp> is used
ramp-0 = "  "
ramp-1 = "  "

# =========================================

